AscentrikProjectWorkflow/Controllers/DashboardController.cs
using AscentrikProjectWorkflow.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AscentrikProjectWorkflow.Controllers
{
    [Authorize]
    public class DashboardController : BaseController
    {
        //
        // GET: /Dashboard/

        public ActionResult Index()
        {
            var model = new DashboardViewModel();
            var result = new List<ProjectViewModel>();
            var userId = Request.Cookies["auth.id"].Value;
            if (User.IsInRole("Admin"))
            {
                result = dashboardModel.GetProjectListForAdmin(DateTime.Now.AddDays(-30), DateTime.Now, 0);
            }
            else
            {
                dashboardModel.GetProjectListForManager(DateTime.Now.AddDays(-30), DateTime.Now, 0, Convert.ToInt32(userId));
            }
            model.Projects = BindDashboardProjectsModel(result);
            model.Clients = clientModel.GetActiveClientList().ToDictionary(x => x.Id, x => x.Code);
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="result"></param>
        /// <returns></returns>
        private DashboardProjectsViewModel BindDashboardProjectsModel(List<ProjectViewModel> result)
        {
            var model = new DashboardProjectsViewModel();

            model.NewProjects = new List<ProjectViewModel>();
            model.InProgressProjects = new List<ProjectViewModel>();
            model.CompleteProjects = new List<ProjectViewModel>();

            if (result != null)
            {
                foreach (var item in result)
                {
                    if (item.ProjectStatus == (int)AscentrikProjectWorkflow.Enum.ProjectStatus.New)
                        model.NewProjects.Add(item);
                    else if (item.ProjectStatus == (int)AscentrikProjectWorkflow.Enum.ProjectStatus.InvoiceRaised || item.ProjectStatus == (int)AscentrikProjectWorkflow.Enum.ProjectStatus.PartlyDeliveredAndInvoiceRaised && item.ProjectStatus == (int)AscentrikProjectWorkflow.Enum.ProjectStatus.PartlyDeliveredAndResearchHalted)
                        model.CompleteProjects.Add(item);
                    else
                        model.InProgressProjects.Add(item);
                }
            }

            if (model.NewProjects.Any())
                model.ShowNewProjects = true;
            if (model.InProgressProjects.Any())
                model.ShowInProgressProjects = true;
            if (model.CompleteProjects.Any())
                model.ShowCompleteProjects = true;


            return model;
        }

        public ActionResult GetProjectById(int id)
        {
            var model = new ProjectDetailViewModel();
            if (User.IsInRole("Admin"))
            {
                model = projectModel.GetProjectById_Admin(id);
            }
            else
            {
                model = projectModel.GetProjectById_Manager(id);
            }

            model.ProjectInfo = BindProjectModel(model.ProjectInfo);

            if (User.IsInRole("Admin"))
            {
                model.ShowCosting = true;
                model.ProjectCosting = BindProjectCostingModel(model.ProjectCosting);

            }
            else
            {
                model.ShowCosting = false;
            }

            return PartialView("_Partial_ProjectAdmin", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public ActionResult AdminDashboard()
        {
            var model = new DashboardViewModel();
            var result = dashboardModel.GetProjectListForAdmin(DateTime.Now.AddDays(-30), DateTime.Now, 0);
            model.Projects = BindDashboardProjectsModel(result);
            model.Clients = clientModel.GetActiveClientList().ToDictionary(x => x.Id, x => x.Code);

            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="startMonth"></param>
        /// <param name="startYear"></param>
        /// <param name="endMonth"></param>
        /// <param name="endYear"></param>
        /// <param name="client"></param>
        /// <returns></returns>
        public ActionResult FilterProjects(int startMonth, int startYear, int endMonth, int endYear, int client)
        {
            var startDate = new DateTime(startYear, startMonth, 1);
            var endDate = new DateTime(endYear, endMonth, 1).AddMonths(1).AddDays(-1);
            var result = dashboardModel.GetProjectListForAdmin(startDate, endDate, client);
            var model = BindDashboardProjectsModel(result);
            return PartialView("_Partial_Projects", model);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Manager")]
        public ActionResult ManagerDashboard()
        {
            return View();
        }

    }
}

AscentrikProjectWorkflow/Controllers/ProjectController.cs
using AscentrikProjectWorkflow.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace AscentrikProjectWorkflow.Controllers
{
    public class ProjectController : BaseController
    {
        //
        // GET: /Project/

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var model = projectModel.GetProjectListForAdmin();
                return View("AdminIndex", model);
            }
            else
            {
                var userId = Request.Cookies["auth.id"].Value;
                var model = projectModel.GetProjectListForManager(Convert.ToInt32(userId));
                return View("ManagerIndex", model);
            }
        }

        #region Create Project

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            var model = new ProjectViewModel();
            model = BindProjectModel(model);
            model.ProjectStatus = (int)AscentrikProjectWorkflow.Enum.ProjectStatus.New;
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize(Roles = "Manager")]
        [HttpPost]
        public ActionResult Create(ProjectViewModel model)
        {
            model = BindProjectModel(model);
            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.CreatedBy = Convert.ToInt32(userId);
                model.CreatedOn = DateTime.Now;
                var result = projectModel.AddProject(model);
                if (result == 0)
                {
                    return RedirectToAction("Index");
                }
                else if (result == 1)
                {
                    ModelState.AddModelError("CustomError", "Invalid project.");
                }
                else if (result == 2)
                {
                    ModelState.AddModelError("CustomError", "This list type is already present in the database.");
                }
                else
                {
                    ModelState.AddModelError("CustomError", "Sorry! Record is not added successfully.");
                }
            }
            else
            {
                StringBuilder result = new StringBuilder();

                foreach (var item in ModelState)
                {
                    string key = item.Key;
                    var errors = item.Value.Errors;

                    foreach (var error in errors)
                    {
                        result.Append(key + " " + error.ErrorMessage);
                    }
                }
                ModelState.AddModelError("CustomError", result.ToString());
            }
            return View(model);
        }

        #endregion

        #region Edit Project

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Edit(int id)
        {
            var model = new ProjectDetailViewModel();
            if (User.IsInRole("Admin"))
            {
                model = projectModel.GetProjectById_Admin(id);
            }
            else
            {
                model = projectModel.GetProjectById_Manager(id);
            }

            model.ProjectInfo = BindProjectModel(model.ProjectInfo);

            if (User.IsInRole("Admin"))
            {
                model.ShowCosting = true;
                model.ProjectCosting = BindProjectCostingModel(model.ProjectCosting);

            }
            else
            {
                model.ShowCosting = false;
            }
            return View("Edit", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="projectInfo"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [HttpPost]
        public ActionResult Edit(ProjectViewModel projectInfo)
        {
            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                projectInfo.EditedBy = Convert.ToInt32(userId);
                projectInfo.EditedOn = DateTime.Now;

                try
                {
                    if (!string.IsNullOrWhiteSpace(projectInfo.ApprovalDateText))
                        projectInfo.ApprovalDate = Convert.ToDateTime(projectInfo.ApprovalDateText);
                }
                catch (Exception ex)
                {
                    return Json(new { status = false, message = "Actual Delivery Date format is incorrect." });
                }

                try
                {
                    if (!string.IsNullOrWhiteSpace(projectInfo.ExpectedDeliveryDateText))
                        projectInfo.ExpectedDeliveryDate = Convert.ToDateTime(projectInfo.ExpectedDeliveryDateText);
                }
                catch (Exception ex)
                {
                    return Json(new { status = false, message = "Expected Delivery Date format is incorrect." });
                }

                var result = projectModel.EditProjectBasicInfo(projectInfo);

                if (result == 0)
                {
                    return Json(new { status = true, message = "Project is updated successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This Project Code is already present in the database." });
                }
                else
                {
                    return Json(new { status = false, message = "Project is not updated successfully." });
                }
            }
            else
            {
                StringBuilder result = new StringBuilder();

                foreach (var item in ModelState)
                {
                    string key = item.Key;
                    var errors = item.Value.Errors;

                    foreach (var error in errors)
                    {
                        result.Append(key + " " + error.ErrorMessage);
                    }
                }
                return Json(new { status = false, message = result });
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="projectInfo"></param>
        /// <returns></returns>
        /// 
        [Authorize]
        [HttpPost]
        public ActionResult TrackProject(ProjectViewModel projectInfo)
        {

            var userId = Request.Cookies["auth.id"].Value;
            projectInfo.EditedBy = Convert.ToInt32(userId);
            projectInfo.EditedOn = DateTime.Now;
            try
            {
                if (!string.IsNullOrWhiteSpace(projectInfo.FTPUploadDateText))
                    projectInfo.FTPUploadDate = Convert.ToDateTime(projectInfo.FTPUploadDateText);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = "FTP Upload Date format is incorrect." });
            }

            try
            {
                if (!string.IsNullOrWhiteSpace(projectInfo.ActualDeliveryDateText))
                    projectInfo.ActualDeliveryDate = Convert.ToDateTime(projectInfo.ActualDeliveryDateText);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = "Actual Delivery Date format is incorrect." });
            }
            var result = projectModel.EditProjectTrackingInfo(projectInfo);

            if (result == 0)
            {
                return Json(new { status = true, message = "Project is updated successfully." });
            }
            else if (result == 1)
            {
                return Json(new { status = false, message = "Please enter all required values." });
            }
            else
            {
                return Json(new { status = false, message = "Project is not updated successfully." });
            }

        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="projectInfo"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditProjectCosting(ProjectCostingViewModel projectInfo)
        {

            var userId = Request.Cookies["auth.id"].Value;
            projectInfo.EditedBy = Convert.ToInt32(userId);
            projectInfo.EditedOn = DateTime.Now;
            try
            {
                if (!string.IsNullOrWhiteSpace(projectInfo.InvoiceDateText))
                    projectInfo.InvoiceDate = Convert.ToDateTime(projectInfo.InvoiceDateText);
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = "FTP Upload Date format is incorrect." });
            }


            var result = projectModel.EditProjectCostingInfo(projectInfo);

            if (result == 0)
            {
                return Json(new { status = true, message = "Project costing is updated successfully." });
            }
            else if (result == 1)
            {
                return Json(new { status = false, message = "Please enter all required values." });
            }
            else
            {

AscentrikProjectWorkflow/Views/Dashboard/Index.cshtml
@model AscentrikProjectWorkflow.ViewModel.DashboardViewModel

@{
    ViewBag.Title = "Admin Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section HeaderPanel {
    <div class="headerPanel">
        <div class="content-wrapper">
            <div class="floarL leftAlign"><a href="javascript:void(0);" id="lnkModifySearch">Modify Search</a></div>
            <div class="floatR rightAlign">You have searched for: Client All, for the period from Jan 2014 to Oct 2014 </div>
        </div>
    </div>
}
<div class="clear"></div>
<div class="featured searchPanel">
    <div class="content-wrapper">
        <p>
            <div class="floarL" style="width: 30%">
                Start Month: 
                <select class="dropdown" id="ddlStartMonth">
                    <option value="1">Jan</option>
                    <option value="2">Feb</option>
                    <option value="3">Mar</option>
                    <option value="4">Apr</option>
                    <option value="5">May</option>
                    <option value="6">Jun</option>
                    <option value="7">Jul</option>
                    <option value="8">Aug</option>
                    <option value="9">Sep</option>
                    <option value="10">Oct</option>
                    <option value="11">Nov</option>
                    <option value="12">Dec</option>
                </select>
                <select class="dropdown" id="ddlStartYear">
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                </select>
            </div>
            <div class="floarL" style="width: 30%">
                End Month: 
                <select class="dropdown" id="ddlEndMonth">
                    <option value="1">Jan</option>
                    <option value="2">Feb</option>
                    <option value="3">Mar</option>
                    <option value="4">Apr</option>
                    <option value="5">May</option>
                    <option value="6">Jun</option>
                    <option value="7">Jul</option>
                    <option value="8">Aug</option>
                    <option value="9">Sep</option>
                    <option value="10">Oct</option>
                    <option value="11">Nov</option>
                    <option value="12">Dec</option>
                </select>
                <select class="dropdown" id="ddlEndYear">
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                </select>
            </div>
            <div class="floarL" style="width: 30%">
                Client:
                 @Html.DropDownList("Client", new SelectList(Model.Clients, "Key", "Value", 0), "--Select--", new { @class = "dropdown", @style = "width: 200px;" })
            </div>
            <div class="floatR" style="width: 10%">
                <button type="button" id="btnSearch" class="btn btn-primary" value="Search">Search</button>
            </div>
            <div class="clear"></div>
        </p>
    </div>
</div>

<div id="divProjects">
    @{Html.RenderPartial("_Partial_Projects", Model.Projects);}
</div>
@Html.Hidden("FilterProjUri", Url.Action("FilterProjects", "Dashboard"))

<div class="modal bootstrap-dialog size-normal type-primary fade in" id="projectModel" tabindex="-1" role="dialog" aria-labelledby="listModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="projDetail">

        </div>
    </div>
</div>

<script type="text/javascript">
    $('#btnSearch').click(function () {
        var startMonth = $('#ddlStartMonth').val();
        var startYear = $('#ddlStartYear').val();
        var endMonth = $('#ddlEndMonth').val();
        var endYear = $('#ddlEndYear').val();
        var client = $('#Client').val();
        if ($.trim(client) == "")
            client = 0;
        ShowLoader();
        var url = $('#FilterProjUri').val();
        $.ajax({
            url: url,
            type: "GET",
            data: { startMonth: startMonth, startYear: startYear, endMonth: endMonth, endYear: endYear, client: client },
            success: function (sendresponse) {
                HideLoader();
                $('#divProjects').html(sendresponse);
            },
            error: function (xhr, err) {
                HideLoader();
                ShowPopupMsg("Sorry some error occured.");
            }
        });
    });
</script>

AscentrikProjectWorkflow/Views/Dashboard/_Partial_ProjectAdmin.cshtml
@model AscentrikProjectWorkflow.ViewModel.ProjectDetailViewModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title bootstrap-dialog-title" id="listModalLabel">@Model.ProjectInfo.Name</h3>
    </div>
    <div class="modal-body">
        @using (Ajax.BeginForm("Edit", "Project", new AjaxOptions
{
    HttpMethod = "POST",
    OnBegin = "onCreateBegin",
    OnSuccess = "onCreateSuccess",
    OnFailure = "onCreateFailure"
}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.ValidationMessage("CustomError")

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Status</th>
                        <td>@Html.DropDownListFor(model => model.ProjectInfo.ProjectStatus, new SelectList(Model.ProjectInfo.StatusList, "Key", "Value", Model.ProjectInfo.ProjectStatus), "--Select--", new { @class = "dropdown" })</td>
                        <td>@Html.ValidationMessageFor(model => model.ProjectInfo.ProjectStatus)</td>
                    </tr>

                    <tr>
                        <th>No Of Records Deliverd</th>
                        <td>@Html.TextBoxFor(model => model.ProjectInfo.NoOfRecordsDeliverd)</td>
                        <td>@Html.ValidationMessageFor(model => model.ProjectInfo.NoOfRecordsDeliverd)</td>
                    </tr>

                    <tr>
                        <th>Duplicate Records Founds</th>
                        <td>@Html.TextBoxFor(model => model.ProjectInfo.DuplicateFounds)</td>
                        <td>@Html.ValidationMessageFor(model => model.ProjectInfo.DuplicateFounds)</td>
                    </tr>

                    <tr>
                        <th>Cost Per Record</th>
                        <td>@Html.TextBoxFor(model => model.ProjectCosting.CostPerRecord)</td>
                        <td>@Html.ValidationMessageFor(model => model.ProjectCosting.CostPerRecord)</td>
                    </tr>
                    
                    <tr>
                        <th>Actual Delivery Date</th>
                        <td>@Html.TextBoxFor(model => model.ProjectInfo.ActualDeliveryDateText, new { @class = "datepicker" }) <span>(dd-mm-yyyy)</span></td>
                        <td>@Html.ValidationMessageFor(model => model.ProjectInfo.ActualDeliveryDateText)</td>
                    </tr>

                </tbody>
            </table>
        }
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
</div>

AscentrikProjectWorkflow/Views/Dashboard/_Partial_Projects.cshtml
@model AscentrikProjectWorkflow.ViewModel.DashboardProjectsViewModel

<div class="projects">

    @if (Model.ShowInProgressProjects)
    {
        <h3>Current  Projects<small> (@Model.InProgressProjects.Count() projects)</small></h3>
        <div class="projectSection">
            <ul class="projectTile">
                @foreach (var item in Model.InProgressProjects)
                {
                    <li class="item currentProjectTile shadow">
                        <div class="firstDiv">
                            <div class="projectCode">@item.ProjectCode</div>
                            <div class="listCode">@item.List.Code (@item.List.Client.Code)</div>
                            <div class="records">@item.NoOfRecordsDeliverd.GetValueOrDefault() records out of @item.RecordsToBeResearched.GetValueOrDefault()</div>
                        </div>
                        <div class="secondDiv">
                            <div class="description">@item.ProjectBrief</div>
                            <div class="links">
                                <a class="showDetail" href="@Url.Action("Edit", "Project", new { id = item.Id })" code="@item.Id">Show Details</a>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
        <div class="clear"></div>
    }

    @if (Model.ShowNewProjects)
    {
        <h3>New Projects <small>(@Model.NewProjects.Count() projects)</small></h3>
        <div class="projectSection">
            <ul class="projectTile">
                @foreach (var item in Model.NewProjects)
                {
                    <li class="item newProjectTile shadow">
                        <div class="firstDiv">
                            <div class="projectCode">@item.ProjectCode</div>
                            <div class="listCode">@item.List.Code (@item.List.Client.Code)</div>
                            <div class="records">@item.NoOfRecordsDeliverd.GetValueOrDefault() records out of @item.RecordsToBeResearched.GetValueOrDefault()</div>
                        </div>
                        <div class="secondDiv">
                            <div class="description">@item.ProjectBrief</div>
                            <div class="links">
                                <a class="showDetail"  href="@Url.Action("Edit", "Project", new { id = item.Id })" code="@item.Id">Show Details</a>
                            </div>
                        </div>
                    </li>
                }

            </ul>
        </div>
        <div class="clear"></div>
    }

    @if (Model.ShowCompleteProjects)
    {
        <h3>Completed Projects<small> (@Model.CompleteProjects.Count() projects)</small></h3>
        <div class="projectSection">
            <ul class="projectTile">
                @foreach (var item in Model.NewProjects)
                {
                    <li class="item completeProjectTile shadow">
                        <div class="firstDiv">
                            <div class="projectCode">@item.ProjectCode</div>
                            <div class="listCode">@item.List.Code (@item.List.Client.Code)</div>
                            <div class="records">@item.NoOfRecordsDeliverd.GetValueOrDefault() records out of @item.RecordsToBeResearched.GetValueOrDefault()</div>
                        </div>
                        <div class="secondDiv">
                            <div class="description">@item.ProjectBrief</div>
                            <div class="links">
                                <a class="showDetail" href="@Url.Action("Edit", "Project", new { id = item.Id })" code="@item.Id">Show Details</a>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
        <div class="clear"></div>
    }

    @if (!Model.ShowNewProjects && !Model.ShowInProgressProjects && !Model.ShowCompleteProjects)
    {
        <h3>Sorry! No project to display.</h3>
    }
</div>
@Html.Hidden("GetProjectUri", Url.Action("GetProjectById", "Dashboard"))
<script type="text/javascript">
    //$('.showDetail').click(function () {
    //    var id = $(this).attr("code");
    //    var url = $('#GetProjectUri').val();
    //    $('#projDetail').html("");
    //    ShowLoader();
    //    $.ajax({
    //        url: url,
    //        type: "GET",
    //        data: { id: id },
    //        success: function (sendresponse) {
    //            HideLoader();
    //            $('#projDetail').html(sendresponse)
    //        },
    //        error: function (xhr, err) {
    //            HideLoader();
    //            ShowPopupMsg("Sorry some error occured.");
    //            return false;
    //        }
    //    });
    //});

</script>