AscentrikProjectWorkflow/Controllers/ClientController.cs
using AscentrikProjectWorkflow.Models;
using AscentrikProjectWorkflow.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AscentrikProjectWorkflow.Controllers
{
    [Authorize]
    public class ClientController : BaseController
    {
        //
        // GET: /Client/

        public ActionResult Index()
        {
            var model = new List<ClientViewModel>();
            model = clientModel.GetClientList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ClientViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.CreatedBy = Convert.ToInt32(userId);
                model.CreatedOn = DateTime.Now;
                var result = clientModel.AddClient(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is added successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This client code is already present in the database." });
                }
                else
                {
                    return Json(new { status = false, message = "Record is not added successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            var model = clientModel.GetClientById(id);
            
            return PartialView("_Partial_ClientEditor", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(ClientViewModel model)
        {

            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.EditedBy = Convert.ToInt32(userId);
                model.EditedOn = DateTime.Now;
                var result = clientModel.EditClient(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is edited successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This client code is already present in the database." });
                }
                else
                {
                    return Json(new { status = false, message = "Record is not edited successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var result = clientModel.DeleteClient(id);
            if (result == 0)
            {
                return Json(new { status = true, message = "Record is deleted successfully." });
            }
            else if (result == 1)
            {
                return Json(new { status = false, message = "Invalid client." });
            }
            else if (result == 2)
            {
                return Json(new { status = false, message = "This client is already associated with some lists. You cannot removed this client" });
            }
            else
            {
                return Json(new { status = false, message = "Sorry some error occured." });
            }
        }

    }
}

AscentrikProjectWorkflow/Controllers/IndexController.cs
using AscentrikProjectWorkflow.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tesseris.Web.SimpleSecurity;

namespace AscentrikProjectWorkflow.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        internal readonly DashboardModel dashboardModel = new DashboardModel();
        public ActionResult Index()
        {
            var result = SimpleSecurityProvider.Current.Register("kangude.sandeep@gmail.com", "password", "1", "6", true);
            return View();
        }

    }
}

AscentrikProjectWorkflow/Controllers/ListController.cs
using AscentrikProjectWorkflow.Models;
using AscentrikProjectWorkflow.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AscentrikProjectWorkflow.Controllers
{
    [Authorize]
    public class ListController : BaseController
    {
        public ListController()
        {}

        
        #region LIST TYPE

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult ListTypes()
        {
            var lstLists = listModel.GetListTypes();
            return View(lstLists);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateListType()
        {
            var model = new ListTypeViewModel();
            return PartialView("CreateListType", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateListType(ListTypeViewModel model)
        {

            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.CreatedBy = Convert.ToInt32(userId);
                model.CreatedOn = DateTime.Now;
                var result = listModel.AddListType(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is added successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This list type is already present in the database." });
                }
                else
                {
                    return Json(new { status = false, message = "Record is not added successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult EditListType(int id)
        {
            var model = listModel.GetListTypeById(id);
            return PartialView("EditListType", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditListType(ListTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.EditedBy = Convert.ToInt32(userId);
                model.EditedOn = DateTime.Now;
                var result = listModel.EditListType(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is updated successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This list type is already present in the database." });
                }
                else if (result == 3)
                {
                    return Json(new { status = false, message = "This list type you are trying to modify is not present in the database." });
                }
                else if (result == 4)
                {
                    return Json(new { status = false, message = "Cannot inactive this list type. Because it is assigened to few Lists." });
                }
                else
                {
                    return Json(new { status = false, message = "Sorry, Record is not updated successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteListType(int id)
        {
            var result = listModel.DeleteListType(id);
            if (result == 0)
            {
                return Json(new { status = true, message = "Record is deleted successfully." });
            }
            else if (result == 1)
            {
                return Json(new { status = false, message = "Invalid list type." });
            }
            else if (result == 2)
            {
                return Json(new { status = false, message = "This list type is already associated with some lists. You cannot removed this list type." });
            }
            else
            {
                return Json(new { status = false, message = "Sorry some error occured." });
            }
        }

        #endregion


        #region LIST

        //
        // GET: /List/
        public ActionResult Index()
        {
            var lstLists = listModel.GetLists();
            return View(lstLists);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateList()
        {
            var model = new ListViewModel();
            model.Clients = clientModel.GetActiveClientList().ToDictionary(x => x.Id, x => x.Code); ///new Dictionary<int, string>();
            model.ListTypes = listModel.GetActiveListTypes().ToDictionary(x => x.Id, x => x.Type); ;
            return PartialView("CreateList", model); 
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateList(ListViewModel model)
        {

            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.CreatedBy = Convert.ToInt32(userId);
                model.CreatedOn = DateTime.Now;
                var result = listModel.AddList(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is added successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This list code is already present in the database." });
                }
                else
                {
                    return Json(new { status = false, message = "Record is not added successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult EditList(int id)
        {
            var model = listModel.GetListById(id);
            model.Clients = clientModel.GetActiveClientList().ToDictionary(x => x.Id, x => x.Code); ///new Dictionary<int, string>();
            model.ListTypes = listModel.GetActiveListTypes().ToDictionary(x => x.Id, x => x.Type); ;
            return PartialView("EditList", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditList(ListViewModel model)
        {

            if (ModelState.IsValid)
            {
                var userId = Request.Cookies["auth.id"].Value;
                model.EditedBy = Convert.ToInt32(userId);
                model.EditedOn = DateTime.Now;
                var result = listModel.EditList(model);
                if (result == 0)
                {
                    return Json(new { status = true, message = "Record is updated successfully." });
                }
                else if (result == 1)
                {
                    return Json(new { status = false, message = "Please enter all required values." });
                }
                else if (result == 2)
                {
                    return Json(new { status = false, message = "This list code is already present in the database." });
                }
                else if (result == 3)
                {
                    return Json(new { status = false, message = "This list you are trying to modify is not present in the database." });
                }
                else if (result == 4)
                {
                    return Json(new { status = false, message = "Cannot change the client of this list. Because it is assigened to few projects." });
                }
                else if (result == 5)
                {
                    return Json(new { status = false, message = "Cannot inactive this list. Because it is assigened to few projects." });
                }
                else
                {
                    return Json(new { status = false, message = "Sorry, Record is not updated successfully." });
                }
            }
            return Json(new { status = false, message = "Please enter all required values." });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteList(int id)
        {
            var result = listModel.DeleteList(id);
            if (result == 0)
            {

AscentrikProjectWorkflow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Ascentrik Project Workflow</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Bootstrap/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("Ascentrik Project Workflow", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">

                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="activeMenu" id="mnuDashboard">@Html.ActionLink("Dashboard", "Index", "Home")</li>
                            <li id="mnuClient">@Html.ActionLink("Clients", "Index", "Client")</li>
                            <li id="mnuLists">@Html.ActionLink("Lists", "Index", "List")</li>
                            <li id="mnuProjects">@Html.ActionLink("Projects", "Index", "Project")</li>
                            <li id="mnuUsers">@Html.ActionLink("Users", "Index", "User")</li>
                        }
                        else
                        {
                            <li class="activeMenu" id="mnuDashboard">@Html.ActionLink("Dashboard", "Index", "Home")</li>
                            <li id="mnuLists">@Html.ActionLink("Lists", "Index", "List")</li>
                            <li id="mnuProjects">@Html.ActionLink("Projects", "Index", "Project")</li>
                        }

                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("HeaderPanel", required: false)
        <section class="content-wrapper clear-fix mainContent">
            @RenderBody()
        </section>
    </div>
    <div class="modal bootstrap-dialog size-normal type-primary fade in" id="loaderModal" tabindex="-1" role="dialog" aria-labelledby="listModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title bootstrap-dialog-title">Please wait...</h3>
                </div>
                <div class="modal-body" style="text-align: center;">
                    <img src="~/Images/loading.gif" />
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <div class="modal bootstrap-dialog size-normal type-primary fade in" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModelLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" onclick="HidePopupMsg()"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h3 class="modal-title bootstrap-dialog-title">Message for you</h3>
                </div>
                <div class="modal-body grayMsg" id="msgDiv">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="HidePopupMsg()">OK</button>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/common.js"></script>

    <script type="text/javascript">
        $('#lnkModifySearch').click(function () {
            $('.searchPanel').slideToggle('slow');
        });

    </script>
</body>
</html>

AscentrikProjectWorkflow/Views/Shared/_Partial_ActiveInActive.cshtml
@model bool

@if (Model)
{
    <span class="active">Active</span>
}
else
{
    <span class="inactive">In-Active</span>
}